### ISSUE TITLE
Android Back to Home: java.lang.NullPointerException

### ISSUE THREAD

**Issue by jinaiyuanbaojie** [rhymelph/r_upgrade#13]
the log shows:
```
 Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.plugin.common.MethodChannel.setMethodCallHandler(io.flutter.plugin.common.MethodChannel$MethodCallHandler)' on a null object reference
        at com.example.r_upgrade.RUpgradePlugin.onDetachedFromEngine(RUpgradePlugin.java:62)
        at io.flutter.embedding.engine.FlutterEnginePluginRegistry.remove(FlutterEnginePluginRegistry.java:252)
        at io.flutter.embedding.engine.FlutterEnginePluginRegistry.remove(FlutterEnginePluginRegistry.java:260)
```
The code locates at
```java
    @Override
    public void onDetachedFromEngine(@NonNull FlutterPluginBinding binding) {
        Intent intent = new Intent(binding.getApplicationContext(), UpgradeService.class);
        binding.getApplicationContext().stopService(intent);
        if (upgradeManager != null) {
            upgradeManager.dispose();
        }
        if (hotUpgradeManager != null) {
            hotUpgradeManager.dispose();
        }
        _channel.setMethodCallHandler(null);  // this is line 62. 
        _channel = null;
    }
```

**Comment by rhymelph** [comment]
well done. you can use new version(v0.2.6) try again.

**Comment by jinaiyuanbaojie** [comment]
> well done. you can use new version(v0.2.6) try again.

Thanks for your effort. It works well now~
