### ISSUE TITLE
空指针了。

### ISSUE THREAD

**Issue by JarvanMo** [rhymelph/r_upgrade#21]
```
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void java.util.Timer.cancel()' on a null object reference
        at com.example.r_upgrade.common.UpgradeManager$3.onReceive(UpgradeManager.java:314)
        at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1122)
        at android.os.Handler.handleCallback(Handler.java:751) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6119) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
```

**Comment by JarvanMo** [comment]
emm，好吧，不是这个库的问题。但也是有点关系，当另一个库也调用了系统的下载器就会出现这个空指针，我觉得有必要判断一下了。

**Comment by rhymelph** [comment]
好的

**Comment by rhymelph** [comment]
v0.3.2 version
