### ISSUE TITLE
App Crash on INCREMENT Patch update.

### ISSUE THREAD

**Issue by canewsin** [rhymelph/r_upgrade#36]
log cat 
```
05-14 19:36:58.865  1662  1881 I ActivityTaskManager: Fully drawn in.canews.movieroar/.MainActivity: +1s559ms
05-14 19:36:58.871 30945  8094 I anews.movieroa: Waiting for a blocking GC ProfileSaver
05-14 19:36:58.888 30945  8203 I DynamiteModule: Considering local module providerinstaller:0 and remote module providerinstaller:0
05-14 19:36:58.888 30945  8203 W ProviderInstaller: Failed to load providerinstaller module: No acceptable module found. Local version is 0 and remote version is 0.
05-14 19:36:58.903 30945  8203 I anews.movieroa: The ClassLoaderContext is a special shared library.
05-14 19:36:58.908 30945  8203 I anews.movieroa: The ClassLoaderContext is a special shared library.
05-14 19:36:58.945 30945  8203 V NativeCrypto: Registering com/google/android/gms/org/conscrypt/NativeCrypto's 287 native methods...
05-14 19:36:58.951  1339  2064 E statsd  : Found dropped events: 1 error -19 last atom tag 240 from uid 10510
05-14 19:36:58.961 30945  8203 I ProviderInstaller: Installed default security provider GmsCore_OpenSSL
05-14 19:36:58.976  1662  3772 D WifiNetworkFactory: got request NetworkRequest [ TRACK_DEFAULT id=1454, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10510 AdministratorUids: [] RequestorUid: 10510 RequestorPackageName: in.canews.movieroar] ] with score 60 and providerId 6
05-14 19:36:58.976  1662  3772 D UntrustedWifiNetworkFactory: got request NetworkRequest [ TRACK_DEFAULT id=1454, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10510 AdministratorUids: [] RequestorUid: 10510 RequestorPackageName: in.canews.movieroar] ] with score 60 and providerId 605-14 19:36:58.977  4391  4391 D PhoneSwitcherNetworkRequstListener: got request NetworkRequest [ TRACK_DEFAULT id=1454, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10510 AdministratorUids: [] RequestorUid: 10510 RequestorPackageName: in.canews.movieroar] ] with score 60 and providerId 6
05-14 19:36:58.979  1662  3819 D WIFI_AWARE_FACTORY: got request NetworkRequest [ TRACK_DEFAULT id=1454, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10510 AdministratorUids: [] RequestorUid: 10510 RequestorPackageName: in.canews.movieroar] ] with score 60 and providerId 6
05-14 19:36:58.979  1662  3820 D Ethernet: got request NetworkRequest [ TRACK_DEFAULT id=1454, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10510 AdministratorUids: [] RequestorUid: 10510 RequestorPackageName: in.canews.movieroar] ] with score 60 and providerId 6
05-14 19:36:59.301 30945  8192 D r_upgrade.Service: run: code=200
05-14 19:36:59.301 30945  8192 D r_upgrade.Service: run: maxLength:10232472
05-14 19:36:59.414   837  8650 D qc_adm  : ns 2627761 > expected_ns 2000000 (skipped 77)
05-14 19:36:59.423   837  8650 D qc_adm  : ns 2601875 > expected_ns 2000000 (skipped 77)
05-14 19:36:59.772 30945  8194 D r_upgrade.Service: handlerDownloadRunning: running queryTask: 下载中
05-14 19:36:59.772 30945  8194 D r_upgrade.Service: url: https://github.com/canewsin/test/releases/download/0/inc.patch
05-14 19:36:59.772 30945  8194 D r_upgrade.Service: ============>total:10232472，progress:1482203，14.17% , 1405.62kb/s , 预计：6s
05-14 19:36:59.800  5465  5465 D BoundBrokerSvc: onUnbind: Intent { act=com.google.android.gms.measurement.START pkg=com.google.android.gms }
05-14 19:36:59.853 20248 20287 D QCNEJ/WlanStaInfoRelay: Received action: android.net.wifi.RSSI_CHANGED
05-14 19:36:59.856  4308  6985 D QCNEJ/WlanStaInfoRelay: Received action: android.net.wifi.RSSI_CHANGED
05-14 19:36:59.911 10427 10484 I CarrierServices: [8038] bze.e: (PEv2-SM-130103966): DisabledState: event Connectivity event [null]
05-14 19:36:59.911 10427 10500 I CarrierServices: [8040] bsw.d: Connected state: [1], networkType: [WIFI]
05-14 19:36:59.926 10427 10502 I CarrierServices: [8041] cfn.m: No RCS Configuration was found in Bugle for simID: redacted-pii:sim_id[20-chars]
05-14 19:36:59.986  1662  1662 D NotificationService: 0|in.canews.movieroar|2|null|10510: granting content://settings/system/notification_sound
05-14 22:09:00.689     0     0 I         : Alarmtimer { AlarmManager', '44710671'}
05-14 19:37:00.272   854  1486 I SDM     : HWCDisplayBuiltIn::parseOutputBuffer: w 1080 h 2340 stride 1088 size 10186752 Bpp 4
05-14 19:37:00.273 30945  8194 D r_upgrade.Service: handlerDownloadRunning: running queryTask: 下载中
05-14 19:37:00.273 30945  8194 D r_upgrade.Service: url: https://github.com/canewsin/test/releases/download/0/inc.patch
05-14 19:37:00.273 30945  8194 D r_upgrade.Service: ============>total:10232472，progress:3464667，33.66% , 3870.97kb/s , 预计：2s
05-14 19:37:00.771 30945  8194 D r_upgrade.Service: handlerDownloadRunning: running queryTask: 下载中
05-14 19:37:00.771 30945  8194 D r_upgrade.Service: url: https://github.com/canewsin/test/releases/download/0/inc.patch
05-14 19:37:00.771 30945  8194 D r_upgrade.Service: ============>total:10232472，progress:5529051，53.96% , 4080.97kb/s , 预计：1s
05-14 19:37:01.271 30945  8194 D r_upgrade.Service: handlerDownloadRunning: running queryTask: 下载中
05-14 19:37:01.271 30945  8194 D r_upgrade.Service: url: https://github.com/canewsin/test/releases/download/0/inc.patch
05-14 19:37:01.271 30945  8194 D r_upgrade.Service: ============>total:10232472，progress:7773659，75.97% , 4428.28kb/s , 预计：1s
05-14 19:37:01.773 30945  8194 D r_upgrade.Service: handlerDownloadRunning: running queryTask: 下载中
05-14 19:37:01.773 30945  8194 D r_upgrade.Service: url: https://github.com/canewsin/test/releases/download/0/inc.patch
05-14 19:37:01.773 30945  8194 D r_upgrade.Service: ============>total:10232472，progress:9838043，95.99% , 4024.14kb/s , 预计：0s
05-14 19:37:01.858 30945  8192 D r_upgrade.Service: handlerDownloadFinish: finish
05-14 19:36:59.990  1662  1662 D NotificationService: 0|in.canews.movieroar|2|null|10510: granting content://settings/system/notification_sound
05-14 19:37:02.333  5465  5465 D BoundBrokerSvc: onBind: Intent { act=com.google.android.gms.measurement.START pkg=com.google.android.gms }
05-14 19:37:02.333  5465  5465 D BoundBrokerSvc: Loading bound service for intent: Intent { act=com.google.android.gms.measurement.START pkg=com.google.android.gms }
05-14 19:37:02.376  1173  8074 I iorapd  : Perfetto TraceBuffer saved to file: /data/misc/iorapd/in.canews.movieroar/1/in.canews.movieroar.MainActivity/raw_traces/1621001222375156961.perfetto_trace.pb
05-14 19:37:02.401  8366  8403 W FA      : Analytics storage consent denied; will not get app instance id
05-14 19:37:02.483  8366  8430 W System.err: java.io.FileNotFoundException: /jacoco.exec: open failed: EROFS (Read-only file system)
05-14 19:37:02.483  8366  8430 W System.err:    at libcore.io.IoBridge.open(IoBridge.java:492)
05-14 19:37:02.483  8366  8430 W System.err:    at java.io.FileOutputStream.<init>(FileOutputStream.java:236)
05-14 19:37:02.483  8366  8430 W System.err:    at w.c.a.a.b.h.a.a(SourceFile:1)
05-14 19:37:02.483  8366  8430 W System.err:    at w.c.a.a.b.h.a.startup(SourceFile:6)
05-14 19:37:02.483  8366  8430 W System.err:    at w.c.a.a.b.a.startup(SourceFile:5)
05-14 19:37:02.483  8366  8430 W System.err:    at w.c.a.a.b.a.getInstance(SourceFile:3)
05-14 19:37:02.483  8366  8430 W System.err:    at w.c.a.a.b.e.<clinit>(SourceFile:2)
05-14 19:37:02.483  8366  8430 W System.err:    at w.c.a.a.b.e.getProbes(SourceFile:1)
05-14 19:37:02.483  8366  8430 W System.err:    at e.m.b.c.j2.n0.a(Unknown Source:13)
05-14 19:37:02.483  8366  8430 W System.err:    at e.m.b.c.j2.n0.<clinit>(Unknown Source:0)
05-14 19:37:02.483  8366  8430 W System.err:    at e.m.b.c.j2.n0.getUserAgent(Unknown Source:0)
05-14 19:37:02.483  8366  8430 W System.err:    at com.wynk.atvdownloader.download.ATVDownloadHelper.<init>(SourceFile:3)
05-14 19:37:02.484  8366  8430 W System.err:    at com.wynk.atvdownloader.download.ATVDownloadHelper$Companion$1.invoke(SourceFile:1)
05-14 19:37:02.484  8366  8430 W System.err:    at com.wynk.atvdownloader.download.ATVDownloadHelper$Companion$1.invoke(SourceFile:2)
05-14 19:37:02.484  8366  8430 W System.err:    at e.w.a.e.a.getInstance(SourceFile:4)
05-14 19:37:02.484  8366  8430 W System.err:    at tv.accedo.wynk.android.airtel.WynkApplication.e(SourceFile:1)
05-14 19:37:02.484  8366  8430 W System.err:    at tv.accedo.wynk.android.airtel.WynkApplication.access$initAtvDownloader(SourceFile:1)
05-14 19:37:02.484  8366  8430 W System.err:    at tv.accedo.wynk.android.airtel.WynkApplication$initLibraries$1.invokeSuspend(SourceFile:22)
05-14 19:37:02.484  8366  8430 W System.err:    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:3)
05-14 19:37:02.484  8366  8430 W System.err:    at r.a.u0.run(SourceFile:18)
05-14 19:37:02.484  8366  8430 W System.err:    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(SourceFile:1)
05-14 19:37:02.484  8366  8430 W System.err:    at kotlinx.coroutines.scheduling.CoroutineScheduler$b.a(SourceFile:17)
05-14 19:37:02.484  8366  8430 W System.err:    at kotlinx.coroutines.scheduling.CoroutineScheduler$b.d(SourceFile:4)
05-14 19:37:02.484  8366  8430 W System.err:    at kotlinx.coroutines.scheduling.CoroutineScheduler$b.run(SourceFile:1)
05-14 19:37:02.484  8366  8430 W System.err: Caused by: android.system.ErrnoException: open failed: EROFS (Read-only file system)
05-14 19:37:02.484  8366  8430 W System.err:    at libcore.io.Linux.open(Native Method)
05-14 19:37:02.484  8366  8430 W System.err:    at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
05-14 19:37:02.484  8366  8430 W System.err:    at libcore.io.BlockGuardOs.open(BlockGuardOs.java:254)
05-14 19:37:02.484  8366  8430 W System.err:    at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
05-14 19:37:02.484  8366  8430 W System.err:    at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7542)
05-14 19:37:02.484  8366  8430 W System.err:    at libcore.io.IoBridge.open(IoBridge.java:478)
05-14 19:37:02.484  8366  8430 W System.err:    ... 23 more
05-14 22:09:03.212     0     0 I IRQ 6   : no longer affine to CPU6
05-14 22:09:03.246     0     0 I         : Alarmtimer { AlarmManager', '44710671'}
05-14 22:09:03.248     0     0 I         : Alarmtimer { Binder:1662_5', '44710671'}
05-14 22:09:03.248     0     0 I         : Alarmtimer { AlarmManager', '44710671'}
05-14 22:09:03.271     0     0 I         : Alarmtimer { system_server', '44710671'}
05-14 19:37:02.592  1662  3772 D WifiNetworkFactory: got request NetworkRequest [ TRACK_DEFAULT id=1455, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10452 AdministratorUids: [] RequestorUid: 10452 RequestorPackageName: tv.accedo.airtel.wynk] ] with score 60 and providerId 6
05-14 19:37:02.592  1662  3772 D UntrustedWifiNetworkFactory: got request NetworkRequest [ TRACK_DEFAULT id=1455, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10452 AdministratorUids: [] RequestorUid: 10452 RequestorPackageName: tv.accedo.airtel.wynk] ] with score 60 and providerId 6
05-14 19:37:02.593  1662  3819 D WIFI_AWARE_FACTORY: got request NetworkRequest [ TRACK_DEFAULT id=1455, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10452 AdministratorUids: [] RequestorUid: 10452 RequestorPackageName: tv.accedo.airtel.wynk] ] with score 60 and providerId 6
05-14 19:37:02.593  1662  3820 D Ethernet: got request NetworkRequest [ TRACK_DEFAULT id=1455, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10452 AdministratorUids: [] RequestorUid: 10452 RequestorPackageName: tv.accedo.airtel.wynk] ] with score 60 and providerId 6
05-14 19:37:02.593  4391  4391 D PhoneSwitcherNetworkRequstListener: got request NetworkRequest [ TRACK_DEFAULT id=1455, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10452 AdministratorUids: [] RequestorUid: 10452 RequestorPackageName: tv.accedo.airtel.wynk] ] with score 60 and providerId 6
05-14 19:37:02.614  4391  4391 D PhoneSwitcherNetworkRequstListener: got request NetworkRequest [ TRACK_DEFAULT id=1456, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10452 AdministratorUids: [] RequestorUid: 10452 RequestorPackageName: tv.accedo.airtel.wynk] ] with score 60 and providerId 6
05-14 19:37:02.615  1662  3819 D WIFI_AWARE_FACTORY: got request NetworkRequest [ TRACK_DEFAULT id=1456, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10452 AdministratorUids: [] RequestorUid: 10452 RequestorPackageName: tv.accedo.airtel.wynk] ] with score 60 and providerId 6
05-14 19:37:02.615  1662  3772 D WifiNetworkFactory: got request NetworkRequest [ TRACK_DEFAULT id=1456, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10452 AdministratorUids: [] RequestorUid: 10452 RequestorPackageName: tv.accedo.airtel.wynk] ] with score 60 and providerId 6
05-14 19:37:02.615  1662  3772 D UntrustedWifiNetworkFactory: got request NetworkRequest [ TRACK_DEFAULT id=1456, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10452 AdministratorUids: [] RequestorUid: 10452 RequestorPackageName: tv.accedo.airtel.wynk] ] with score 60 and providerId 6
05-14 19:37:02.615  1662  3820 D Ethernet: got request NetworkRequest [ TRACK_DEFAULT id=1456, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10452 AdministratorUids: [] RequestorUid: 10452 RequestorPackageName: tv.accedo.airtel.wynk] ] with score 60 and providerId 6
05-14 19:37:02.619  5556  5556 W AppIndexingScheduler: [main] Full index started
05-14 19:37:02.661  1662  3987 W ActivityManager: Foreground service started from background can not have location/camera/microphone access: service tv.accedo.airtel.wynk/tv.accedo.wynk.android.blocks.service.download.AppDownloadService
05-14 19:37:02.772  8366  8396 W FA      : Value is too long; discarded. Value kind, name, value length: user property, productId, 68
05-14 19:37:02.703  1662  3987 W ActivityManager: Foreground service started from background can not have location/camera/microphone access: service tv.accedo.airtel.wynk/tv.accedo.wynk.android.blocks.service.download.AppDownloadService
05-14 19:37:02.863  1662  1662 D NotificationService: 0|tv.accedo.airtel.wynk|1|null|10452: granting content://settings/system/notification_sound05-14 19:37:03.024   854  1486 I SDM     : HWCDisplayBuiltIn::parseOutputBuffer: w 1080 h 2340 stride 1088 size 10186752 Bpp 4
05-14 22:09:04.836     0     0 I chatty  : uid=0(root) logd identical 5 lines
05-14 22:09:04.836     0     0 E msm_bus_device 16e0000.ad-hoc-bus: TCS Busy, retrying RPMH message send
05-14 22:09:04.893     0     0 I IRQ 6   : no longer affine to CPU5
05-14 22:09:04.953     0     0 I FG      : soc_work_fn: adjust_soc: s 34 r 134521 i -1264 v 3978 t 382 cc 417 m 0x56
05-14 19:37:04.344  4662  5961 W CCTFlatFileLogStore: Excessive logging: 2048 events, 462165 bytes from log source PEOPLE_AUTOCOMPLETE last 653s
05-14 22:09:06.233     0     0 I FG      : fg_battery_soc_smooth_tracking: soc:34, last_soc:34, raw_soc:34, soc_changed:1.
05-14 22:09:06.233     0     0 I FG      : soc_monitor_work: soc:34, raw_soc:34, c:-1276366, s:1
05-14 19:37:05.716   863  3834 I WifiHAL : event received NL80211_CMD_VENDOR, vendor_id = 0x1374, subcmd = 0xd
05-14 19:37:05.717  1356  1356 I cnss-daemon: nl80211 response handler invoked
05-14 19:37:05.717  1356  1356 I cnss-daemon: nl80211_response_handler: cmd 103, vendorID 4980, subcmd 13  received
05-14 19:37:05.731  1662  2225 W InputDispatcher: channel '617baf1 in.canews.movieroar/in.canews.movieroar.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
05-14 19:37:05.732  1662  2225 E InputDispatcher: channel '617baf1 in.canews.movieroar/in.canews.movieroar.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
05-14 19:37:02.864  1662  1662 I chatty  : uid=1000 system_server identical 5 lines
05-14 19:37:02.864  1662  1662 D NotificationService: 0|tv.accedo.airtel.wynk|1|null|10452: granting content://settings/system/notification_sound05-14 19:37:05.739  1662  4702 D ConnectivityService: ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ TRACK_DEFAULT id=1453, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10510 AdministratorUids: [] RequestorUid: 10510 RequestorPackageName: in.canews.movieroar] ], android.os.BinderProxy@3dd784a)
05-14 19:37:05.739  1662  4685 D ConnectivityService: ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ TRACK_DEFAULT id=1454, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10510 AdministratorUids: [] RequestorUid: 10510 RequestorPackageName: in.canews.movieroar] ], android.os.BinderProxy@32ef3bb)
05-14 19:37:05.740  1662  5660 I ActivityManager: Process in.canews.movieroar (pid 30945) has died: fg  TOP
05-14 19:37:05.743  1662  5660 W ActivityManager: Scheduling restart of crashed service in.canews.movieroar/com.example.r_upgrade.common.UpgradeService in 1000ms for start-requested
05-14 19:37:05.744  8131  8131 I cr_ChildProcessService: Destroying ChildProcessService pid=8131
05-14 19:37:05.745   771   771 I Zygote  : Process 30945 exited cleanly (1)
05-14 19:37:05.746  8131  8131 I ocessService0:: System.exit called, status: 0
05-14 19:37:05.746  8131  8131 I AndroidRuntime: VM exiting with result code 0, cleanup skipped.
05-14 19:37:05.747  1662  5658 I WindowManager: WIN DEATH: Window{617baf1 u0 in.canews.movieroar/in.canews.movieroar.MainActivity}
05-14 19:37:05.748  1662  5658 W InputDispatcher: Attempted to unregister already unregistered input channel '617baf1 in.canews.movieroar/in.canews.movieroar.MainActivity (server)'
05-14 19:37:05.760  1662  5660 W ActivityTaskManager: Force removing ActivityRecord{14febd6 u0 in.canews.movieroar/.MainActivity t469}: app died, no saved state
05-14 19:37:05.781  1662  5660 I ActivityManager: Killing 8131:com.google.android.webview:sandboxed_process0:org.chromium.content.app.SandboxedProcessService0:0/u0a510i75 (adj 0): isolated not needed
05-14 19:37:05.785  1662  1896 I libprocessgroup: Successfully killed process cgroup uid 10510 pid 30945 in 44ms
05-14 19:37:05.785  1662  1896 I libprocessgroup: Successfully killed process cgroup uid 99075 pid 8131 in 0ms
05-14 19:37:05.789  1662  1866 W ActivityManager: setHasOverlayUi called on unknown pid: 30945
05-14 19:37:05.790  3754  3970 I BtGatt.ScanManager: msg.what = 6
05-14 19:37:05.814  4205  4205 I Zygote  : Process 8131 exited cleanly (0)
```

**Comment by canewsin** [comment]
i traced error and it crashed at https://github.com/rhymelph/r_upgrade/blob/master/android/src/main/java/com/example/r_upgrade/common/IncrementUpgradeManager.java#L39

**Comment by canewsin** [comment]
@rhymelph

**Comment by rhymelph** [comment]
Do you want to perform incremental updates according to the process?
Step 1: ` flutter build APK -- release ` This is the old APK
Step 2: after adding your code, execute 'flutter build APK -- release'. This is a new APK
Step 3: download the files in the warehouse https://github.com/rhymelph/r_ upgrade/releases/download/v0.3.0/bsdiff
Step 4: execute the command '. / bsdiff old.apk new.apk increment.patch`
Step 5: upload the generated 'increment. Patch' to the server
Step 6: install the APK generated in the first step, then check the update and download increment

**Comment by canewsin** [comment]
yes i do the same thing, but provided bsdiff didn't worked for me, so i used various bsdiff binaries from other sources.
i modified r_update lib to use another bsdiff, but it is cumbersome to me, could you provide bsdiff  and bspatch jni source code, so that it is easy to debug ?

**Comment by canewsin** [comment]
i found various problems in lib itself, first is bsdiff compatibility, another one is you are saving .patch file to downloads dir but on android 11, device i was testing is crashing on patching due to non availability of source, i didn't get root cause, i  thought it was file access permission causing such issue, thus i modified patch download path and new apk path to app external private dir.

**Comment by nieshuo** [comment]
I have the same problem,my andorid version is 11,my flutter version is 2.2.1,my r_upgrade version is 0.3.4,When I choose to click incremental update,The file storage address is  /android/data/my app package names/files/Download/increment.patch

**Comment by nieshuo** [comment]
but when I choose full update,the file is saved in the same address,it can be installed normally
