### ISSUE TITLE
Unexpected Exception On Application Close

### ISSUE THREAD

**Issue by liemfs** [rhymelph/r_upgrade#50]
### Flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.22000.434], locale en-ID)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[✗] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[!] Android Studio (not installed)
[✓] VS Code, 64-bit edition (version 1.63.2)
[✓] Connected device (2 available)
```
### Exception
```
E/ActivityThread( 6400): Activity rick.roll.MainActivity has leaked IntentReceiver com.example.r_upgrade.common.UpgradeManager$3@1b77883 that was originally registered here. Are you missing a call to unregisterReceiver()?
E/ActivityThread( 6400): android.app.IntentReceiverLeaked: Activity rick.roll.caraka.MainActivity has leaked IntentReceiver com.example.r_upgrade.common.UpgradeManager$3@1b77883 that was originally registered here. Are you missing a call to unregisterReceiver()?
E/ActivityThread( 6400): 	at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1429)
E/ActivityThread( 6400): 	at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:1210)
E/ActivityThread( 6400): 	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1476)
E/ActivityThread( 6400): 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1449)
E/ActivityThread( 6400): 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1437)
E/ActivityThread( 6400): 	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:623)
E/ActivityThread( 6400): 	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:623)
E/ActivityThread( 6400): 	at com.example.r_upgrade.common.UpgradeManager.<init>(UpgradeManager.java:101)
E/ActivityThread( 6400): 	at com.example.r_upgrade.RUpgradePlugin.<init>(RUpgradePlugin.java:39)
E/ActivityThread( 6400): 	at com.example.r_upgrade.RUpgradePlugin.onAttachedToActivity(RUpgradePlugin.java:71)
E/ActivityThread( 6400): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.add(FlutterEngineConnectionRegistry.java:155)
E/ActivityThread( 6400): 	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:139)
E/ActivityThread( 6400): 	at java.lang.reflect.Method.invoke(Native Method)
E/ActivityThread( 6400): 	at io.flutter.embedding.engine.plugins.util.GeneratedPluginRegister.registerGeneratedPlugins(GeneratedPluginRegister.java:80)
E/ActivityThread( 6400): 	at io.flutter.embedding.android.FlutterActivity.configureFlutterEngine(FlutterActivity.java:1004)
E/ActivityThread( 6400): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:191)
E/ActivityThread( 6400): 	at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:459)
E/ActivityThread( 6400): 	at android.app.Activity.performCreate(Activity.java:7136)
E/ActivityThread( 6400): 	at android.app.Activity.performCreate(Activity.java:7127)
E/ActivityThread( 6400): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
E/ActivityThread( 6400): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
E/ActivityThread( 6400): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
E/ActivityThread( 6400): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
E/ActivityThread( 6400): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
E/ActivityThread( 6400): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
E/ActivityThread( 6400): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
E/ActivityThread( 6400): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/ActivityThread( 6400): 	at android.os.Looper.loop(Looper.java:193)
E/ActivityThread( 6400): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/ActivityThread( 6400): 	at java.lang.reflect.Method.invoke(Native Method)
E/ActivityThread( 6400): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/ActivityThread( 6400): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```
### Step to produce exception

1. Create new Flutter project (default code inside, no changes)
2. Add r_upgrade into pubspec.yaml (latest version, 0.3.7+2)
3. Run project (debug, profile, release doesn't matter)
4. On emulator or device, press back button to close the app (exception will appear in debug console)
5. On some occasion, Android pop-up dialog will appear with this message "MyApp keeps stopping", which is not pleasant for end user

Did some test using r_upgrade v0.3.3 to v0.3.7+2, all of them gave exact same exception

**Comment by ling9400** [comment]
Me too
