### ISSUE TITLE
handlerDownloadFailure: failure,这个问题怎么解决

### ISSUE THREAD

**Issue by 84559221** [rhymelph/r_upgrade#60]
现象描述：
小米5x上昨天测试是好的，可以下载，今天报下面的错误，不能下载。然后同样的代码在小米8上跑还是好的，可以下载。
错误日志：
D/r_upgrade.Service( 5427): onReceive: 当前网络正在连接
W/System.err( 5427): java.io.IOException: Not a directory
W/System.err( 5427): 	at java.io.UnixFileSystem.createFileExclusively0(Native Method)
W/System.err( 5427): 	at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:281)
W/System.err( 5427): 	at java.io.File.createNewFile(File.java:1000)
W/System.err( 5427): 	at com.example.r_upgrade.common.UpgradeService$UpgradeRunnable.run(UpgradeService.java:550)
W/System.err( 5427): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
W/System.err( 5427): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
W/System.err( 5427): 	at java.lang.Thread.run(Thread.java:764)
D/r_upgrade.Service( 5427): handlerDownloadFailure: failure

报错相关核心代码：
      RUpgrade.stream.listen(
          (downloadInfo) => _onDataChanged(downloadInfo, onDataCallback),
          onError: (error, stackTrace) => _onError(error, onDataCallback, stackTrace: stackTrace),
          onDone: () => _onDone(onDataCallback),
          cancelOnError: true
      );
      print("_downloadFromUrl.fileUrl:$fileUrl, fileName:$fileName");
      try {
        _upgradeID = await RUpgrade.upgrade("https://meiyanjiju.com/app/meiyan.apk", fileName: "meiyan.apk", isAutoRequestInstall: true);
        // _upgradeID = await RUpgrade.upgrade(fileUrl, fileName: fileName, isAutoRequestInstall: true);
      } catch(e) {
        print("执行到此,_downloadFromUrl2.e:$e");
      }

**Comment by 84559221** [comment]
另外还有个问题：
异常报错后，onerror没有接收到异常，try~catch也没有捕捉到异常
