### ISSUE TITLE
下载完apk ,安装的时候报错，使用的手机是三星，android 版本6.0.1，

### ISSUE THREAD

**Issue by xiaojiedeVX** [rhymelph/r_upgrade#7]
试了一下，用你的demo 在这个手机上也不行

D/Instrumentation(16066): checkStartActivityResult() : Intent { act=android.intent.action.VIEW dat=content://com.example.r_upgrade_example.fileProvider/external_storage_root/Download/r_upgrade.apk typ=application/vnd.android.package-archive flg=0x10000001 }
D/Instrumentation(16066): checkStartActivityResult() : intent is instance of [Intent].
E/MethodChannel#com.rhyme/r_upgrade_method(16066): Failed to handle method call
E/MethodChannel#com.rhyme/r_upgrade_method(16066): android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=content://com.example.r_upgrade_example.fileProvider/external_storage_root/Download/r_upgrade.apk typ=application/vnd.android.package-archive flg=0x10000001 }
E/MethodChannel#com.rhyme/r_upgrade_method(16066):      at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1879)
E/MethodChannel#com.rhyme/r_upgrade_method(16066):      at android.app.Instrumentation.execStartActivity(Instrumentation.java:1546)
E/MethodChannel#com.rhyme/r_upgrade_method(16066):      at android.app.ContextImpl.startActivity(ContextImpl.java:745)
E/MethodChannel#com.rhyme/r_upgrade_method(16066):      at android.app.ContextImpl.startActivity(ContextImpl.java:727)
E/MethodChannel#com.rhyme/r_upgrade_method(16066):      at android.content.ContextWrapper.startActivity(ContextWrapper.java:345)
E/MethodChannel#com.rhyme/r_upgrade_method(16066):      at android.content.ContextWrapper.startActivity(ContextWrapper.java:345)
E/MethodChannel#com.rhyme/r_upgrade_method(16066):      at com.example.r_upgrade.common.UpgradeManager.installApk(UpgradeManager.java:266)
E/MethodChannel#com.rhyme/r_upgrade_method(16066):      at com.example.r_upgrade.common.UpgradeManager.installApkById(UpgradeManager.java:284)
E/MethodChannel#com.rhyme/r_upgrade_method(16066):      at com.example.r_upgrade.method.RUpgradeMethodEnum$3.handler(RUpgradeMethodEnum.java:33)
E/MethodChannel#com.rhyme/r_upgrade_method(16066):      at com.example.r_upgrade.method.RUpgradeMethodCallHandler.onMethodCall(RUpgradeMethodCallHandler.java:13)
E/MethodChannel#com.rhyme/r_upgrade_method(16066):      at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
E/MethodChannel#com.rhyme/r_upgrade_method(16066):      at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
E/MethodChannel#com.rhyme/r_upgrade_method(16066):      at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
E/MethodChannel#com.rhyme/r_upgrade_method(16066):      at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#com.rhyme/r_upgrade_method(16066):      at android.os.MessageQueue.next(MessageQueue.java:323)
E/MethodChannel#com.rhyme/r_upgrade_method(16066):      at android.os.Looper.loop(Looper.java:135)
E/MethodChannel#com.rhyme/r_upgrade_method(16066):      at android.app.ActivityThread.main(ActivityThread.java:7224)
E/MethodChannel#com.rhyme/r_upgrade_method(16066):      at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#com.rhyme/r_upgrade_method(16066):      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
E/MethodChannel#com.rhyme/r_upgrade_method(16066):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
E/flutter (16066): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, No Activity found to handle Intent { act=android.intent.action.VIEW dat=content://com.example.r_upgrade_example.fileProvider/external_storage_root/Download/r_upgrade.apk typ=application/vnd.android.package-archive flg=0x10000001 }, null)
E/flutter (16066): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter (16066): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
E/flutter (16066): <asynchronous suspension>
E/flutter (16066): #2      RUpgrade.install (package:r_upgrade/r_upgrade.dart:81:33)
E/flutter (16066): #3      _MyAppState._buildAndroidPlatformWidget.<anonymous closure> (package:r_upgrade_example/main.dart:98:47)
E/flutter (16066): #4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:706:14)
E/flutter (16066): #5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:789:36)
E/flutter (16066): #6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter (16066): #7      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:486:11)
E/flutter (16066): #8      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:264:5)
E/flutter (16066): #9      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:236:7)
E/flutter (16066): #10     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
E/flutter (16066): #11     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:222:20)
E/flutter (16066): #12     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter (16066): #13     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter (16066): #14     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter (16066): #15     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter (16066): #16     _rootRunUnary (dart:async/zone.dart:1138:13)
E/flutter (16066): #17     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
E/flutter (16066): #18     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
E/flutter (16066): #19     _invoke1 (dart:ui/hooks.dart:273:10)
E/flutter (16066): #20     _dispatchPointerDataPacket (dart:ui/hooks.dart:182:5)
E/flutter (16066):

**Comment by xiaojiedeVX** [comment]
D/Instrumentation(26617): checkStartActivityResult() : Intent { act=android.intent.action.VIEW dat=content://com.flutter_lswl.fileProvider/external-path/Download/lswl_2.0.0_2.apk typ=application/vnd.android.package-archive flg=0x10000001 }
D/Instrumentation(26617): checkStartActivityResult() : intent is instance of [Intent].
D/AndroidRuntime(26617): Shutting down VM
E/AndroidRuntime(26617): FATAL EXCEPTION: main
E/AndroidRuntime(26617): Process: com.flutter_lswl, PID: 26617
E/AndroidRuntime(26617): java.lang.RuntimeException: Error receiving broadcast Intent { act=com.example.r_upgrade.DOWNLOAD_STATUS flg=0x10 bqHint=4 (has extras) } in com.example.r_upgrade.common.UpgradeManager$2@c95651e
E/AndroidRuntime(26617):        at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1003)
E/AndroidRuntime(26617):        at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime(26617):        at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(26617):        at android.os.Looper.loop(Looper.java:148)
E/AndroidRuntime(26617):        at android.app.ActivityThread.main(ActivityThread.java:7224)
E/AndroidRuntime(26617):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(26617):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
E/AndroidRuntime(26617):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
E/AndroidRuntime(26617): Caused by: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=content://com.flutter_lswl.fileProvider/external-path/Download/lswl_2.0.0_2.apk typ=application/vnd.android.package-archive flg=0x10000001 }
E/AndroidRuntime(26617):        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1879)
E/AndroidRuntime(26617):        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1546)
E/AndroidRuntime(26617):        at android.app.ContextImpl.startActivity(ContextImpl.java:745)
E/AndroidRuntime(26617):        at android.app.ContextImpl.startActivity(ContextImpl.java:727)
E/AndroidRuntime(26617):        at android.content.ContextWrapper.startActivity(ContextWrapper.java:345)
E/AndroidRuntime(26617):        at android.content.ContextWrapper.startActivity(ContextWrapper.java:345)
E/AndroidRuntime(26617):        at com.example.r_upgrade.common.UpgradeManager.installApk(UpgradeManager.java:266)
E/AndroidRuntime(26617):        at com.example.r_upgrade.common.UpgradeManager$2.onReceive(UpgradeManager.java:328)
E/AndroidRuntime(26617):        at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:993)
E/AndroidRuntime(26617):        ... 7 more

**Comment by xiaojiedeVX** [comment]
![image](https://user-images.githubusercontent.com/27721983/77821520-ec469a00-7125-11ea-8e85-3f84dd4b32ee.png)

**Comment by xiaojiedeVX** [comment]
大哥，求救，看不懂原生

**Comment by rhymelph** [comment]
把调用方法`upgrade`的参数`useDownloadManager`设置为`true`试一下

**Comment by rhymelph** [comment]
已解决，请将插件更新到v0.2.1

**Comment by xiaojiedeVX** [comment]
非常感谢，测试了，可以了
