### ISSUE TITLE
因安卓13权限改动无法弹出申请权限的界面

### ISSUE THREAD

**Issue by lan2000** [rhymelph/r_upgrade#76]
r_upgrade 0.4.1

错误日志：

```
D/CompatibilityChangeReporter(21964): Compat change id reported: 78294732; UID 10161; state: ENABLED
E/flutter (21964): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(storagePermission, Read/Write External Storage permission not granted, null, null)
E/flutter (21964): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
E/flutter (21964): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:296:18)
E/flutter (21964): <asynchronous suspension>
E/flutter (21964): #2      _MyAppState.build.<anonymous closure> (package:test_flutter/main.dart:203:30)
E/flutter (21964): <asynchronous suspension>
E/flutter (21964): 

```

权限调整
https://developer.android.com/about/versions/13/behavior-changes-13?hl=zh-cn#granular-media-permissions

**Comment by DevChen** [comment]
waiting for new version to fix the same question

**Comment by rhymelph** [comment]
你是哪个机型, pixel 5 ,android 13版本能拉起权限,可以给个详细的demo,方便排查问题

**Comment by rhymelph** [comment]
如果不能解决,你可以用[permission_handler](https://pub.dev/packages/permission_handler) 先申请权限再开始调用下载方法

**Comment by lan2000** [comment]
> 你是哪个机型, pixel 5 ,android 13版本能拉起权限,可以给个详细的demo,方便排查问题

targetSdkVersion 已经设置33吗，我用的是自带模拟器测试。
